String["toLocaleString"].call(this, {"en":{
    "WiFi": "WiFi connection", 
    "Reauthenticate": "Reauthenticate {0}", 
    "QueryDidntMatchAnyDocuments": "Your query did not match any documents.", 
    "exchangedocument": "Exchange document", 
    "ValueDescription": "Sort on the values of the first computed field", 
    "Forward": "Forward", 
    "ShowMore": "Show more", 
    "ReplyAll": "Reply All", 
    "Today": "Today", 
    "xml": "XML File", 
    "CompleteQuery": "Complete Query", 
    "CELL_2G": "Cellular 2G connection", 
    "Exclude": "Exclude {0}", 
    "CELL_4G": "Cellular 4G connection", 
    "BadUserPass": "Password does not match with user name.", 
    "folder": "Folder", 
    "exchangemessage": "Message", 
    "Reset": "Reset", 
    "OpenInOutlookWhenPossible": "Open in Outlook (when possible)", 
    "Last": "Last", 
    "AlwaysOpenInNewWindow": "Always open results in new window", 
    "Of": "of", 
    "mov": "QuickTime File", 
    "Value": "Value", 
    "EnterExpressionToFilterWith": "Enter Expression To Filter Results With", 
    "Unexclude": "Unexclude {0}", 
    "Or": "OR", 
    "GetStarted": "Get Started", 
    "noResultFor": "No results for {0}", 
    "Less": "Fewer", 
    "AreYouSureDeleteFilter": "Are you sure you want to delete the filter {0} with the expression {1}", 
    "LoginInProgress": "Login in progress, please wait ...", 
    "AlphaDescending": "Value Descending", 
    "ShowingResultsOf": "Result<pl>s</pl> {0}<pl>-{1} </pl>of {2}", 
    "Tab": "Tab", 
    "CannotConnect": "Cannot connect to the server address.", 
    "MostRelevantReplies": "Most Relevant Replies:", 
    "Previous": "Previous", 
    "Retry": "Retry", 
    "From": "From", 
    "Preferences": "Preferences", 
    "ShareQuery": "Share Query", 
    "Create": "Create", 
    "ClientDuration": "Client Duration: {0}", 
    "Next": "Next", 
    "exchangecalendarmessage": "Calendar message", 
    "Reply": "Reply", 
    "ComputedField": "Computed Field", 
    "More": "More", 
    "Username": "Username", 
    "txt": "Text", 
    "Collapse": "Collapse", 
    "Seconds": "in {0} second<pl>s</pl>", 
    "SearchIn": "Search in {0}", 
    "Ascending": "Ascending", 
    "Link": "Link", 
    "DisplayingTheOnlyMessage": "Displaying the only message in this conversation", 
    "EnterTag": "Add Tag", 
    "ShowLess": "Show less", 
    "Me": "Me", 
    "Settings": "Settings", 
    "LinkOpeningSettings": "Link Opening Settings", 
    "ShowFacet": "Show Facet", 
    "ShowAllReplies": "Show All Replies", 
    "ProxyDuration": "Proxy Duration: {0}", 
    "didYouMean": "Did you mean: {0}", 
    "CustomDescription": "Sort based on a custom order", 
    "ChiSquare": "Chi Square", 
    "MostRelevantItems": "Most relevant items:", 
    "Authenticating": "Authenticating {0}...", 
    "EthernetConnection": "Ethernet connection", 
    "Tabs": "Tabs", 
    "xls": "Excel Document", 
    "QuickView": "Quick View", 
    "activedirperson": "Active Directory user", 
    "RelativeFrequencyDescription": "Sort based on the relative frequency of values. Less common values will appear higher", 
    "AndOthers": "and {0} other<pl>s</pl>", 
    "EnterExpressionName": "Enter Expression Name", 
    "ClearFacetState": "Clear facet state", 
    "ProblemPersists": "If the problem persists contact the administrator.", 
    "image": "Image", 
    "Label": "Label", 
    "IndexDuration": "Index Duration: {0}", 
    "ErrorReport": "Error Report", 
    "UnknownConnection": "Unknown connection", 
    "Login": "Log In", 
    "autoCorrectedQueryTo": "Query was automatically corrected to {0}", 
    "exchangeappointment": "Appointment", 
    "zip": "Zip File", 
    "ClearAllFilters": "Clear All Filters", 
    "exchangenote": "Note", 
    "exchangeactivity": "Activity", 
    "ShowAllConversation": "Show All Conversation", 
    "OopsError": "Oops! Something went wrong on the server.", 
    "Search": "Search", 
    "GoBack": "Go Back", 
    "RelativeFrequency": "Relative Frequency", 
    "ShowCompleteThread": "Show Complete Thread", 
    "Nosort": "No Sort", 
    "Expression": "Expression", 
    "exchangeofficecom": "Communications", 
    "And": "AND", 
    "ppt": "PowerPoint Document", 
    "ShowOnlyTopMatchingPosts": "Show Only Top Matching Posts", 
    "CompleteThread": "Complete Thread:", 
    "Done": "Done", 
    "Expand": "Expand", 
    "Close": "Close", 
    "Open": "Open", 
    "Tomorrow": "Tomorrow", 
    "exchangetask": "Task", 
    "FiltersInYourPreferences": "Filters in your preferences", 
    "NoNetworkConnection": "No network connection", 
    "OnlineHelp": "Online Help", 
    "ScoreDescription": "The score is computed from the number of occurrences as well as from the position in the result set.", 
    "Custom": "Custom", 
    "Score": "Score", 
    "SaveFacetState": "Save this facet state", 
    "MoreInfo": "More Information", 
    "SwitchTo": "Switch to {0}", 
    "OccurrencesDescription": "Sort by number of occurrences, with values having the highest number appearing first.", 
    "AllConversation": "All Conversation:", 
    "AlphaAscending": "Value Ascending", 
    "Yesterday": "Yesterday", 
    "CELL": "Cellular connection", 
    "SuggestedResults": "Suggested Results", 
    "html": "HTML File", 
    "Descending": "Descending", 
    "Password": "Password", 
    "ShowOnlyMostRelevantReplies": "Show Only Most Relevant Replies", 
    "Clear": "Clear {0}", 
    "ResultsFilteringExpression": "Results Filtering Expressions", 
    "SkipLogin": "Skip login", 
    "Remove": "Remove", 
    "Caption": "Caption", 
    "SelectTab": "Select Tab", 
    "SuggestedQueries": "Suggested Queries", 
    "MostRelevantPosts": "Most Relevant Posts:", 
    "pdf": "PDF File", 
    "HideFacet": "Hide Facet", 
    "Unavailable": "Unavailable", 
    "PleaseEnterYourCredentials": "Please enter your credentials for {0}.", 
    "SearchFor": "Search for {0}", 
    "doc": "Word Document", 
    "CELL_3G": "Cellular 3G connection", 
    "AllItems": "All items:", 
    "LabelDescription": "Sort alphabetically on the field values.", 
    "Occurrences": "Occurrences", 
    "exchangeperson": "Exchange user", 
    "Duration": "Duration: {0}"
}});
String["locale"] = "en";

/*
 * Globalize Culture en-US
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

var Globalize = window["Globalize"];

Globalize.addCultureInfo( "en-US", "default", {
	name: "en-US",
	englishName: "English (United States)"
});
Globalize.culture("en");

